### ISSUE TITLE
History is not save for a command modified by a recent history search

### ISSUE THREAD

**Issue by GrubbyHalo** [atuinsh/atuin#1039]
I guess the title says it all. If i retrieve a command from a search and modify it then that modified command is not save as can be seen. 

![Peek 2023-06-09 10-42](https://github.com/ellie/atuin/assets/3902125/6f969894-26f9-46d6-9209-5f0c6432286c)

**Comment by pgneogeo** [comment]
I  came here for this problem too.
I use Atuin for 2 things : a great search in the history, and duration of commands to track my time at the end of the week.
But today I noticed that not once I connected to the VPN, which I do every day when I start to work.
That explain the big gaps in my tracking, all commands taken from history are not in the history **again**

**Comment by dcarosone** [comment]
I see this too; recalled and edited commands are not saved as new entries

**Comment by retaildynamics-za** [comment]
Yip. I stopped using atuin around the time I opened this issue because I couldn't be bothered to type out the entire recalled history for the command for it to be saved by atuin. Once this is fixed I'll back to using it in a flash.

**Comment by GrubbyHalo** [comment]
Yip. I stopped using atuin around the time I opened this issue because I couldn't be bothered to type out the entire recalled history for the command for it to be saved by atuin. Once this is fixed I'll back to using it in a flash.

**Comment by LLyaudet** [comment]
In the line of this, I think it would be great to have a key binding in interactive search like Ctrl-':' "alias" Enter select the correct command in history or type anew Enter, that creates a link between an alias/typo/whatever and the correct command :)

**Comment by ellie** [comment]
This should be resolved in `main` now, and I could not replicate with a recent build. Please let me know if you experience this to not be the case!

I'll be releasing v17 (which will include this change) as soon as our mac ARM build machine is back online. That should be in around 2 weeks from now.

**Comment by chrichrichri** [comment]
For me this problem still persists using version 18.0.1: Whenever I edit a command called from atuin history, it is not saved. See also screen recording below. Any ideas?

https://github.com/atuinsh/atuin/assets/103507888/54f90b14-98fc-4290-84c7-8a24fb3fd4c5
